language: node_js
sudo: required
node_js:
    - "6"
install:
    - sudo apt-get update -qq
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -y
    - sudo apt-get upgrade -y
    - sudo apt-get install libstdc++6 -y
    - sudo apt-get install gcc -y
    - sudo apt-get install -qq g++-4.9
    - export CXX="g++-4.9" 
    - g++ -v
    - bash install.bash
script:
    - npm run build
notifications:
    email: never
