language: node_js
dist: trusty
sudo: false
node_js:
    - "6"
addons:
    apt:
        sources:
        - ubuntu toolchain-r-test
        packages:
        - g++-5
install:
    - bash install.bash
script:
    - npm run build
notifications:
    email: never
