language: node_js
sudo: required
node_js:
    - "6"
env:
    - CXX=g++4.9
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.9
install:
    - bash install.bash
script:
    - npm run build
notifications:
    email: never
